// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table_bucket

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration) {
		delta.Add("Spec.EncryptionConfiguration", a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration)
	} else if a.ko.Spec.EncryptionConfiguration != nil && b.ko.Spec.EncryptionConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN) {
			delta.Add("Spec.EncryptionConfiguration.KMSKeyARN", a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN)
		} else if a.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil && b.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil {
			if *a.ko.Spec.EncryptionConfiguration.KMSKeyARN != *b.ko.Spec.EncryptionConfiguration.KMSKeyARN {
				delta.Add("Spec.EncryptionConfiguration.KMSKeyARN", a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.SSEAlgorithm, b.ko.Spec.EncryptionConfiguration.SSEAlgorithm) {
			delta.Add("Spec.EncryptionConfiguration.SSEAlgorithm", a.ko.Spec.EncryptionConfiguration.SSEAlgorithm, b.ko.Spec.EncryptionConfiguration.SSEAlgorithm)
		} else if a.ko.Spec.EncryptionConfiguration.SSEAlgorithm != nil && b.ko.Spec.EncryptionConfiguration.SSEAlgorithm != nil {
			if *a.ko.Spec.EncryptionConfiguration.SSEAlgorithm != *b.ko.Spec.EncryptionConfiguration.SSEAlgorithm {
				delta.Add("Spec.EncryptionConfiguration.SSEAlgorithm", a.ko.Spec.EncryptionConfiguration.SSEAlgorithm, b.ko.Spec.EncryptionConfiguration.SSEAlgorithm)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StorageClassConfiguration, b.ko.Spec.StorageClassConfiguration) {
		delta.Add("Spec.StorageClassConfiguration", a.ko.Spec.StorageClassConfiguration, b.ko.Spec.StorageClassConfiguration)
	} else if a.ko.Spec.StorageClassConfiguration != nil && b.ko.Spec.StorageClassConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.StorageClassConfiguration.StorageClass, b.ko.Spec.StorageClassConfiguration.StorageClass) {
			delta.Add("Spec.StorageClassConfiguration.StorageClass", a.ko.Spec.StorageClassConfiguration.StorageClass, b.ko.Spec.StorageClassConfiguration.StorageClass)
		} else if a.ko.Spec.StorageClassConfiguration.StorageClass != nil && b.ko.Spec.StorageClassConfiguration.StorageClass != nil {
			if *a.ko.Spec.StorageClassConfiguration.StorageClass != *b.ko.Spec.StorageClassConfiguration.StorageClass {
				delta.Add("Spec.StorageClassConfiguration.StorageClass", a.ko.Spec.StorageClassConfiguration.StorageClass, b.ko.Spec.StorageClassConfiguration.StorageClass)
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
