// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration) {
		delta.Add("Spec.EncryptionConfiguration", a.ko.Spec.EncryptionConfiguration, b.ko.Spec.EncryptionConfiguration)
	} else if a.ko.Spec.EncryptionConfiguration != nil && b.ko.Spec.EncryptionConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN) {
			delta.Add("Spec.EncryptionConfiguration.KMSKeyARN", a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN)
		} else if a.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil && b.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil {
			if *a.ko.Spec.EncryptionConfiguration.KMSKeyARN != *b.ko.Spec.EncryptionConfiguration.KMSKeyARN {
				delta.Add("Spec.EncryptionConfiguration.KMSKeyARN", a.ko.Spec.EncryptionConfiguration.KMSKeyARN, b.ko.Spec.EncryptionConfiguration.KMSKeyARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.EncryptionConfiguration.SSEAlgorithm, b.ko.Spec.EncryptionConfiguration.SSEAlgorithm) {
			delta.Add("Spec.EncryptionConfiguration.SSEAlgorithm", a.ko.Spec.EncryptionConfiguration.SSEAlgorithm, b.ko.Spec.EncryptionConfiguration.SSEAlgorithm)
		} else if a.ko.Spec.EncryptionConfiguration.SSEAlgorithm != nil && b.ko.Spec.EncryptionConfiguration.SSEAlgorithm != nil {
			if *a.ko.Spec.EncryptionConfiguration.SSEAlgorithm != *b.ko.Spec.EncryptionConfiguration.SSEAlgorithm {
				delta.Add("Spec.EncryptionConfiguration.SSEAlgorithm", a.ko.Spec.EncryptionConfiguration.SSEAlgorithm, b.ko.Spec.EncryptionConfiguration.SSEAlgorithm)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Format, b.ko.Spec.Format) {
		delta.Add("Spec.Format", a.ko.Spec.Format, b.ko.Spec.Format)
	} else if a.ko.Spec.Format != nil && b.ko.Spec.Format != nil {
		if *a.ko.Spec.Format != *b.ko.Spec.Format {
			delta.Add("Spec.Format", a.ko.Spec.Format, b.ko.Spec.Format)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Metadata, b.ko.Spec.Metadata) {
		delta.Add("Spec.Metadata", a.ko.Spec.Metadata, b.ko.Spec.Metadata)
	} else if a.ko.Spec.Metadata != nil && b.ko.Spec.Metadata != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Metadata.Iceberg, b.ko.Spec.Metadata.Iceberg) {
			delta.Add("Spec.Metadata.Iceberg", a.ko.Spec.Metadata.Iceberg, b.ko.Spec.Metadata.Iceberg)
		} else if a.ko.Spec.Metadata.Iceberg != nil && b.ko.Spec.Metadata.Iceberg != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Metadata.Iceberg.PartitionSpec, b.ko.Spec.Metadata.Iceberg.PartitionSpec) {
				delta.Add("Spec.Metadata.Iceberg.PartitionSpec", a.ko.Spec.Metadata.Iceberg.PartitionSpec, b.ko.Spec.Metadata.Iceberg.PartitionSpec)
			} else if a.ko.Spec.Metadata.Iceberg.PartitionSpec != nil && b.ko.Spec.Metadata.Iceberg.PartitionSpec != nil {
				if len(a.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields) != len(b.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields) {
					delta.Add("Spec.Metadata.Iceberg.PartitionSpec.Fields", a.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields, b.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields)
				} else if len(a.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields) > 0 {
					if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields, b.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields) {
						delta.Add("Spec.Metadata.Iceberg.PartitionSpec.Fields", a.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields, b.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID, b.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID) {
					delta.Add("Spec.Metadata.Iceberg.PartitionSpec.SpecID", a.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID, b.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID)
				} else if a.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID != nil && b.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID != nil {
					if *a.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID != *b.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID {
						delta.Add("Spec.Metadata.Iceberg.PartitionSpec.SpecID", a.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID, b.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID)
					}
				}
			}
			if len(a.ko.Spec.Metadata.Iceberg.Properties) != len(b.ko.Spec.Metadata.Iceberg.Properties) {
				delta.Add("Spec.Metadata.Iceberg.Properties", a.ko.Spec.Metadata.Iceberg.Properties, b.ko.Spec.Metadata.Iceberg.Properties)
			} else if len(a.ko.Spec.Metadata.Iceberg.Properties) > 0 {
				if !ackcompare.MapStringStringPEqual(a.ko.Spec.Metadata.Iceberg.Properties, b.ko.Spec.Metadata.Iceberg.Properties) {
					delta.Add("Spec.Metadata.Iceberg.Properties", a.ko.Spec.Metadata.Iceberg.Properties, b.ko.Spec.Metadata.Iceberg.Properties)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Metadata.Iceberg.Schema, b.ko.Spec.Metadata.Iceberg.Schema) {
				delta.Add("Spec.Metadata.Iceberg.Schema", a.ko.Spec.Metadata.Iceberg.Schema, b.ko.Spec.Metadata.Iceberg.Schema)
			} else if a.ko.Spec.Metadata.Iceberg.Schema != nil && b.ko.Spec.Metadata.Iceberg.Schema != nil {
				if len(a.ko.Spec.Metadata.Iceberg.Schema.Fields) != len(b.ko.Spec.Metadata.Iceberg.Schema.Fields) {
					delta.Add("Spec.Metadata.Iceberg.Schema.Fields", a.ko.Spec.Metadata.Iceberg.Schema.Fields, b.ko.Spec.Metadata.Iceberg.Schema.Fields)
				} else if len(a.ko.Spec.Metadata.Iceberg.Schema.Fields) > 0 {
					if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Metadata.Iceberg.Schema.Fields, b.ko.Spec.Metadata.Iceberg.Schema.Fields) {
						delta.Add("Spec.Metadata.Iceberg.Schema.Fields", a.ko.Spec.Metadata.Iceberg.Schema.Fields, b.ko.Spec.Metadata.Iceberg.Schema.Fields)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Metadata.Iceberg.WriteOrder, b.ko.Spec.Metadata.Iceberg.WriteOrder) {
				delta.Add("Spec.Metadata.Iceberg.WriteOrder", a.ko.Spec.Metadata.Iceberg.WriteOrder, b.ko.Spec.Metadata.Iceberg.WriteOrder)
			} else if a.ko.Spec.Metadata.Iceberg.WriteOrder != nil && b.ko.Spec.Metadata.Iceberg.WriteOrder != nil {
				if len(a.ko.Spec.Metadata.Iceberg.WriteOrder.Fields) != len(b.ko.Spec.Metadata.Iceberg.WriteOrder.Fields) {
					delta.Add("Spec.Metadata.Iceberg.WriteOrder.Fields", a.ko.Spec.Metadata.Iceberg.WriteOrder.Fields, b.ko.Spec.Metadata.Iceberg.WriteOrder.Fields)
				} else if len(a.ko.Spec.Metadata.Iceberg.WriteOrder.Fields) > 0 {
					if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Metadata.Iceberg.WriteOrder.Fields, b.ko.Spec.Metadata.Iceberg.WriteOrder.Fields) {
						delta.Add("Spec.Metadata.Iceberg.WriteOrder.Fields", a.ko.Spec.Metadata.Iceberg.WriteOrder.Fields, b.ko.Spec.Metadata.Iceberg.WriteOrder.Fields)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID, b.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID) {
					delta.Add("Spec.Metadata.Iceberg.WriteOrder.OrderID", a.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID, b.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID)
				} else if a.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID != nil && b.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID != nil {
					if *a.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID != *b.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID {
						delta.Add("Spec.Metadata.Iceberg.WriteOrder.OrderID", a.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID, b.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID)
					}
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Namespace, b.ko.Spec.Namespace) {
		delta.Add("Spec.Namespace", a.ko.Spec.Namespace, b.ko.Spec.Namespace)
	} else if a.ko.Spec.Namespace != nil && b.ko.Spec.Namespace != nil {
		if *a.ko.Spec.Namespace != *b.ko.Spec.Namespace {
			delta.Add("Spec.Namespace", a.ko.Spec.Namespace, b.ko.Spec.Namespace)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.NamespaceRef, b.ko.Spec.NamespaceRef) {
		delta.Add("Spec.NamespaceRef", a.ko.Spec.NamespaceRef, b.ko.Spec.NamespaceRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StorageClassConfiguration, b.ko.Spec.StorageClassConfiguration) {
		delta.Add("Spec.StorageClassConfiguration", a.ko.Spec.StorageClassConfiguration, b.ko.Spec.StorageClassConfiguration)
	} else if a.ko.Spec.StorageClassConfiguration != nil && b.ko.Spec.StorageClassConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.StorageClassConfiguration.StorageClass, b.ko.Spec.StorageClassConfiguration.StorageClass) {
			delta.Add("Spec.StorageClassConfiguration.StorageClass", a.ko.Spec.StorageClassConfiguration.StorageClass, b.ko.Spec.StorageClassConfiguration.StorageClass)
		} else if a.ko.Spec.StorageClassConfiguration.StorageClass != nil && b.ko.Spec.StorageClassConfiguration.StorageClass != nil {
			if *a.ko.Spec.StorageClassConfiguration.StorageClass != *b.ko.Spec.StorageClassConfiguration.StorageClass {
				delta.Add("Spec.StorageClassConfiguration.StorageClass", a.ko.Spec.StorageClassConfiguration.StorageClass, b.ko.Spec.StorageClassConfiguration.StorageClass)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TableBucketARN, b.ko.Spec.TableBucketARN) {
		delta.Add("Spec.TableBucketARN", a.ko.Spec.TableBucketARN, b.ko.Spec.TableBucketARN)
	} else if a.ko.Spec.TableBucketARN != nil && b.ko.Spec.TableBucketARN != nil {
		if *a.ko.Spec.TableBucketARN != *b.ko.Spec.TableBucketARN {
			delta.Add("Spec.TableBucketARN", a.ko.Spec.TableBucketARN, b.ko.Spec.TableBucketARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TableBucketRef, b.ko.Spec.TableBucketRef) {
		delta.Add("Spec.TableBucketRef", a.ko.Spec.TableBucketRef, b.ko.Spec.TableBucketRef)
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
