// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package table

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/s3tables"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/s3tables/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/s3tables-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Table{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// Read the table by its stable ARN rather than the name triplet. GetTable
	// accepts the triplet (tableBucketARN + namespace + name) OR tableArn, but
	// not both. Keying off the ARN lets GetTable return the CURRENT AWS name, so
	// a change to spec.name surfaces as a delta and drives RenameTable. Falls
	// back to the name triplet before the ARN is known (first reconcile).
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		input.TableArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
		input.TableBucketARN = nil
		input.Namespace = nil
		input.Name = nil
	} else {
		input.TableArn = nil
	}

	var resp *svcsdk.GetTableOutput
	resp, err = rm.sdkapi.GetTable(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetTable", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "NotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Format != "" {
		ko.Spec.Format = aws.String(string(resp.Format))
	} else {
		ko.Spec.Format = nil
	}
	if resp.MetadataLocation != nil {
		ko.Spec.MetadataLocation = resp.MetadataLocation
	} else {
		ko.Spec.MetadataLocation = nil
	}
	if resp.ModifiedAt != nil {
		ko.Status.ModifiedAt = &metav1.Time{*resp.ModifiedAt}
	} else {
		ko.Status.ModifiedAt = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.TableARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.TableARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.Type != "" {
		ko.Status.Type = aws.String(string(resp.Type))
	} else {
		ko.Status.Type = nil
	}
	if resp.VersionToken != nil {
		ko.Status.VersionToken = resp.VersionToken
	} else {
		ko.Status.VersionToken = nil
	}
	if resp.WarehouseLocation != nil {
		ko.Status.WarehouseLocation = resp.WarehouseLocation
	} else {
		ko.Status.WarehouseLocation = nil
	}

	rm.setStatusDefaults(ko)
	// GetTable returns `namespace` as a list; bridge the first element back into
	// the scalar Spec.Namespace so observed state matches desired.
	if len(resp.Namespace) > 0 {
		ko.Spec.Namespace = &resp.Namespace[0]
	}
	// The generated output mapping skips NamespaceId/TableBucketId: the
	// code-generator output loop matches SDK member names (`NamespaceId`,
	// `TableBucketId`) against the resource field keys, which are stored with
	// ACK's `ID` initialism (`NamespaceID`, `TableBucketID`), so the members
	// don't match and are skipped. (Unrelated to the `namespace` list field
	// dropped via ignore.field_paths — see TableBucket, which hits the same skip
	// with no ignore rule.) Populate those read-only status fields here.
	if resp.NamespaceId != nil {
		ko.Status.NamespaceID = resp.NamespaceId
	}
	if resp.TableBucketId != nil {
		ko.Status.TableBucketID = resp.TableBucketId
	}
	// GetTable does not return tags; fetch them via ListTagsForResource so the
	// delta against Spec.Tags is accurate and we avoid spurious deltas.
	if err := rm.setResourceTags(ctx, ko); err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return false
}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetTableInput, error) {
	res := &svcsdk.GetTableInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Namespace != nil {
		res.Namespace = r.ko.Spec.Namespace
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.TableArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.TableBucketARN != nil {
		res.TableBucketARN = r.ko.Spec.TableBucketARN
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateTableOutput
	_ = resp
	resp, err = rm.sdkapi.CreateTable(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateTable", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.TableARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.TableARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.VersionToken != nil {
		ko.Status.VersionToken = resp.VersionToken
	} else {
		ko.Status.VersionToken = nil
	}

	rm.setStatusDefaults(ko)
	// metadataLocation is not part of CreateTable; it can only be applied via
	// the dedicated UpdateTableMetadataLocation API. When the user supplies a
	// desired metadataLocation, requeue so the next reconciliation observes the
	// delta and customUpdateTable syncs it via UpdateTableMetadataLocation.
	if desired.ko.Spec.MetadataLocation != nil {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, aws.String("table created, requeue for updates"), nil)
		err = ackrequeue.NeededAfter(fmt.Errorf("Reconciling to sync additional fields"), time.Second)
		return &resource{ko}, err
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateTableInput, error) {
	res := &svcsdk.CreateTableInput{}

	if r.ko.Spec.EncryptionConfiguration != nil {
		f0 := &svcsdktypes.EncryptionConfiguration{}
		if r.ko.Spec.EncryptionConfiguration.KMSKeyARN != nil {
			f0.KmsKeyArn = r.ko.Spec.EncryptionConfiguration.KMSKeyARN
		}
		if r.ko.Spec.EncryptionConfiguration.SSEAlgorithm != nil {
			f0.SseAlgorithm = svcsdktypes.SSEAlgorithm(*r.ko.Spec.EncryptionConfiguration.SSEAlgorithm)
		}
		res.EncryptionConfiguration = f0
	}
	if r.ko.Spec.Format != nil {
		res.Format = svcsdktypes.OpenTableFormat(*r.ko.Spec.Format)
	}
	if r.ko.Spec.Metadata != nil {
		var f2 svcsdktypes.TableMetadata
		isInterfaceSet := false
		if r.ko.Spec.Metadata.Iceberg != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Iceberg"))
			}
			f2f0Parent := &svcsdktypes.TableMetadataMemberIceberg{}
			f2f0 := &svcsdktypes.IcebergMetadata{}
			if r.ko.Spec.Metadata.Iceberg.PartitionSpec != nil {
				f2f0f0 := &svcsdktypes.IcebergPartitionSpec{}
				if r.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields != nil {
					f2f0f0f0 := []svcsdktypes.IcebergPartitionField{}
					for _, f2f0f0f0iter := range r.ko.Spec.Metadata.Iceberg.PartitionSpec.Fields {
						f2f0f0f0elem := &svcsdktypes.IcebergPartitionField{}
						if f2f0f0f0iter.FieldID != nil {
							fieldIDCopy0 := *f2f0f0f0iter.FieldID
							if fieldIDCopy0 > math.MaxInt32 || fieldIDCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field fieldId is of type int32")
							}
							fieldIDCopy := int32(fieldIDCopy0)
							f2f0f0f0elem.FieldId = &fieldIDCopy
						}
						if f2f0f0f0iter.Name != nil {
							f2f0f0f0elem.Name = f2f0f0f0iter.Name
						}
						if f2f0f0f0iter.SourceID != nil {
							sourceIDCopy0 := *f2f0f0f0iter.SourceID
							if sourceIDCopy0 > math.MaxInt32 || sourceIDCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field sourceId is of type int32")
							}
							sourceIDCopy := int32(sourceIDCopy0)
							f2f0f0f0elem.SourceId = &sourceIDCopy
						}
						if f2f0f0f0iter.Transform != nil {
							f2f0f0f0elem.Transform = f2f0f0f0iter.Transform
						}
						f2f0f0f0 = append(f2f0f0f0, *f2f0f0f0elem)
					}
					f2f0f0.Fields = f2f0f0f0
				}
				if r.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID != nil {
					specIDCopy0 := *r.ko.Spec.Metadata.Iceberg.PartitionSpec.SpecID
					if specIDCopy0 > math.MaxInt32 || specIDCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field specId is of type int32")
					}
					specIDCopy := int32(specIDCopy0)
					f2f0f0.SpecId = &specIDCopy
				}
				f2f0.PartitionSpec = f2f0f0
			}
			if r.ko.Spec.Metadata.Iceberg.Properties != nil {
				f2f0.Properties = aws.ToStringMap(r.ko.Spec.Metadata.Iceberg.Properties)
			}
			if r.ko.Spec.Metadata.Iceberg.Schema != nil {
				f2f0f2 := &svcsdktypes.IcebergSchema{}
				if r.ko.Spec.Metadata.Iceberg.Schema.Fields != nil {
					f2f0f2f0 := []svcsdktypes.SchemaField{}
					for _, f2f0f2f0iter := range r.ko.Spec.Metadata.Iceberg.Schema.Fields {
						f2f0f2f0elem := &svcsdktypes.SchemaField{}
						if f2f0f2f0iter.ID != nil {
							idCopy0 := *f2f0f2f0iter.ID
							if idCopy0 > math.MaxInt32 || idCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field id is of type int32")
							}
							idCopy := int32(idCopy0)
							f2f0f2f0elem.Id = &idCopy
						}
						if f2f0f2f0iter.Name != nil {
							f2f0f2f0elem.Name = f2f0f2f0iter.Name
						}
						if f2f0f2f0iter.Required != nil {
							f2f0f2f0elem.Required = *f2f0f2f0iter.Required
						}
						if f2f0f2f0iter.Type != nil {
							f2f0f2f0elem.Type = f2f0f2f0iter.Type
						}
						f2f0f2f0 = append(f2f0f2f0, *f2f0f2f0elem)
					}
					f2f0f2.Fields = f2f0f2f0
				}
				f2f0.Schema = f2f0f2
			}
			if r.ko.Spec.Metadata.Iceberg.WriteOrder != nil {
				f2f0f3 := &svcsdktypes.IcebergSortOrder{}
				if r.ko.Spec.Metadata.Iceberg.WriteOrder.Fields != nil {
					f2f0f3f0 := []svcsdktypes.IcebergSortField{}
					for _, f2f0f3f0iter := range r.ko.Spec.Metadata.Iceberg.WriteOrder.Fields {
						f2f0f3f0elem := &svcsdktypes.IcebergSortField{}
						if f2f0f3f0iter.Direction != nil {
							f2f0f3f0elem.Direction = svcsdktypes.IcebergSortDirection(*f2f0f3f0iter.Direction)
						}
						if f2f0f3f0iter.NullOrder != nil {
							f2f0f3f0elem.NullOrder = svcsdktypes.IcebergNullOrder(*f2f0f3f0iter.NullOrder)
						}
						if f2f0f3f0iter.SourceID != nil {
							sourceIDCopy0 := *f2f0f3f0iter.SourceID
							if sourceIDCopy0 > math.MaxInt32 || sourceIDCopy0 < math.MinInt32 {
								return nil, fmt.Errorf("error: field sourceId is of type int32")
							}
							sourceIDCopy := int32(sourceIDCopy0)
							f2f0f3f0elem.SourceId = &sourceIDCopy
						}
						if f2f0f3f0iter.Transform != nil {
							f2f0f3f0elem.Transform = f2f0f3f0iter.Transform
						}
						f2f0f3f0 = append(f2f0f3f0, *f2f0f3f0elem)
					}
					f2f0f3.Fields = f2f0f3f0
				}
				if r.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID != nil {
					orderIDCopy0 := *r.ko.Spec.Metadata.Iceberg.WriteOrder.OrderID
					if orderIDCopy0 > math.MaxInt32 || orderIDCopy0 < math.MinInt32 {
						return nil, fmt.Errorf("error: field orderId is of type int32")
					}
					orderIDCopy := int32(orderIDCopy0)
					f2f0f3.OrderId = &orderIDCopy
				}
				f2f0.WriteOrder = f2f0f3
			}
			f2f0Parent.Value = *f2f0
			f2 = f2f0Parent
			isInterfaceSet = true
		}
		res.Metadata = f2
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Namespace != nil {
		res.Namespace = r.ko.Spec.Namespace
	}
	if r.ko.Spec.StorageClassConfiguration != nil {
		f5 := &svcsdktypes.StorageClassConfiguration{}
		if r.ko.Spec.StorageClassConfiguration.StorageClass != nil {
			f5.StorageClass = svcsdktypes.StorageClass(*r.ko.Spec.StorageClassConfiguration.StorageClass)
		}
		res.StorageClassConfiguration = f5
	}
	if r.ko.Spec.TableBucketARN != nil {
		res.TableBucketARN = r.ko.Spec.TableBucketARN
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateTable(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteTableOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteTable(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteTable", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteTableInput, error) {
	res := &svcsdk.DeleteTableInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Namespace != nil {
		res.Namespace = r.ko.Spec.Namespace
	}
	if r.ko.Spec.TableBucketARN != nil {
		res.TableBucketARN = r.ko.Spec.TableBucketARN
	}
	if r.ko.Status.VersionToken != nil {
		res.VersionToken = r.ko.Status.VersionToken
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Table,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "BadRequestException":
		return true
	default:
		return false
	}
}
