// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type IcebergCompactionStrategy string

const (
	IcebergCompactionStrategy_auto    IcebergCompactionStrategy = "auto"
	IcebergCompactionStrategy_binpack IcebergCompactionStrategy = "binpack"
	IcebergCompactionStrategy_sort    IcebergCompactionStrategy = "sort"
	IcebergCompactionStrategy_z_order IcebergCompactionStrategy = "z-order"
)

type IcebergNullOrder string

const (
	IcebergNullOrder_nulls_first IcebergNullOrder = "nulls-first"
	IcebergNullOrder_nulls_last  IcebergNullOrder = "nulls-last"
)

type IcebergSortDirection string

const (
	IcebergSortDirection_asc  IcebergSortDirection = "asc"
	IcebergSortDirection_desc IcebergSortDirection = "desc"
)

type JobStatus string

const (
	JobStatus_Disabled    JobStatus = "Disabled"
	JobStatus_Failed      JobStatus = "Failed"
	JobStatus_Not_Yet_Run JobStatus = "Not_Yet_Run"
	JobStatus_Successful  JobStatus = "Successful"
)

type MaintenanceStatus string

const (
	MaintenanceStatus_disabled MaintenanceStatus = "disabled"
	MaintenanceStatus_enabled  MaintenanceStatus = "enabled"
)

type OpenTableFormat string

const (
	OpenTableFormat_ICEBERG OpenTableFormat = "ICEBERG"
)

type ReplicationStatus string

const (
	ReplicationStatus_completed ReplicationStatus = "completed"
	ReplicationStatus_failed    ReplicationStatus = "failed"
	ReplicationStatus_pending   ReplicationStatus = "pending"
)

type SSEAlgorithm string

const (
	SSEAlgorithm_AES256  SSEAlgorithm = "AES256"
	SSEAlgorithm_aws_kms SSEAlgorithm = "aws:kms"
)

type StorageClass string

const (
	StorageClass_INTELLIGENT_TIERING StorageClass = "INTELLIGENT_TIERING"
	StorageClass_STANDARD            StorageClass = "STANDARD"
)

type TableBucketMaintenanceType string

const (
	TableBucketMaintenanceType_icebergUnreferencedFileRemoval TableBucketMaintenanceType = "icebergUnreferencedFileRemoval"
)

type TableBucketType string

const (
	TableBucketType_aws      TableBucketType = "aws"
	TableBucketType_customer TableBucketType = "customer"
)

type TableMaintenanceJobType string

const (
	TableMaintenanceJobType_icebergCompaction              TableMaintenanceJobType = "icebergCompaction"
	TableMaintenanceJobType_icebergSnapshotManagement      TableMaintenanceJobType = "icebergSnapshotManagement"
	TableMaintenanceJobType_icebergUnreferencedFileRemoval TableMaintenanceJobType = "icebergUnreferencedFileRemoval"
)

type TableMaintenanceType string

const (
	TableMaintenanceType_icebergCompaction         TableMaintenanceType = "icebergCompaction"
	TableMaintenanceType_icebergSnapshotManagement TableMaintenanceType = "icebergSnapshotManagement"
)

type TableRecordExpirationJobStatus string

const (
	TableRecordExpirationJobStatus_Disabled   TableRecordExpirationJobStatus = "Disabled"
	TableRecordExpirationJobStatus_Failed     TableRecordExpirationJobStatus = "Failed"
	TableRecordExpirationJobStatus_NotYetRun  TableRecordExpirationJobStatus = "NotYetRun"
	TableRecordExpirationJobStatus_Successful TableRecordExpirationJobStatus = "Successful"
)

type TableRecordExpirationStatus string

const (
	TableRecordExpirationStatus_disabled TableRecordExpirationStatus = "disabled"
	TableRecordExpirationStatus_enabled  TableRecordExpirationStatus = "enabled"
)

type TableType string

const (
	TableType_aws      TableType = "aws"
	TableType_customer TableType = "customer"
)
