// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NamespaceSpec defines the desired state of Namespace.
type NamespaceSpec struct {

	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	Name *string `json:"name,omitempty"`
	// The Amazon Resource Name (ARN) of the table bucket to create the namespace
	// in.
	//
	// Regex Pattern: `^(arn:aws[-a-z0-9]*:[a-z0-9]+:[-a-z0-9]*:[0-9]{12}:bucket/[a-z0-9_-]{3,63})$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	TableBucketARN *string                                  `json:"tableBucketARN,omitempty"`
	TableBucketRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"tableBucketRef,omitempty"`
}

// NamespaceStatus defines the observed state of Namespace
type NamespaceStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time the namespace was created at.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The ID of the account that created the namespace.
	//
	// Regex Pattern: `^[0-9].*$`
	// +kubebuilder:validation:Optional
	CreatedBy *string `json:"createdBy,omitempty"`
	// The unique identifier of the namespace.
	// +kubebuilder:validation:Optional
	NamespaceID *string `json:"namespaceID,omitempty"`
	// The unique identifier of the table bucket containing this namespace.
	// +kubebuilder:validation:Optional
	TableBucketID *string `json:"tableBucketID,omitempty"`
}

// Namespace is the Schema for the Namespaces API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Namespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NamespaceSpec   `json:"spec,omitempty"`
	Status            NamespaceStatus `json:"status,omitempty"`
}

// NamespaceList contains a list of Namespace
// +kubebuilder:object:root=true
type NamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Namespace `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Namespace{}, &NamespaceList{})
}
