// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TableBucketSpec defines the desired state of TableBucket.
type TableBucketSpec struct {

	// The encryption configuration to use for the table bucket. This configuration
	// specifies the default encryption settings that will be applied to all tables
	// created in this bucket unless overridden at the table level. The configuration
	// includes the encryption algorithm and, if using SSE-KMS, the KMS key to use.
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	// The name for the table bucket.
	//
	// Regex Pattern: `^[0-9a-z-]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The default storage class configuration for the table bucket. This configuration
	// will be applied to all new tables created in this bucket unless overridden
	// at the table level. If not specified, the service default storage class will
	// be used.
	StorageClassConfiguration *StorageClassConfiguration `json:"storageClassConfiguration,omitempty"`
	// A map of user-defined tags that you would like to apply to the table bucket
	// that you are creating. A tag is a key-value pair that you apply to your resources.
	// Tags can help you organize and control access to resources. For more information,
	// see Tagging for cost allocation or attribute-based access control (ABAC)
	// (https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging.html).
	//
	// You must have the s3tables:TagResource permission in addition to s3tables:CreateTableBucket
	// permisson to create a table bucket with tags.
	Tags map[string]*string `json:"tags,omitempty"`
}

// TableBucketStatus defines the observed state of TableBucket
type TableBucketStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time the table bucket was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The type of the table bucket.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty"`
}

// TableBucket is the Schema for the TableBuckets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type TableBucket struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TableBucketSpec   `json:"spec,omitempty"`
	Status            TableBucketStatus `json:"status,omitempty"`
}

// TableBucketList contains a list of TableBucket
// +kubebuilder:object:root=true
type TableBucketList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TableBucket `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TableBucket{}, &TableBucketList{})
}
