// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TableSpec defines the desired state of Table.
type TableSpec struct {

	// The encryption configuration to use for the table. This configuration specifies
	// the encryption algorithm and, if using SSE-KMS, the KMS key to use for encrypting
	// the table.
	//
	// If you choose SSE-KMS encryption you must grant the S3 Tables maintenance
	// principal access to your KMS key. For more information, see Permissions requirements
	// for S3 Tables SSE-KMS encryption (https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-tables-kms-permissions.html).
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	EncryptionConfiguration *EncryptionConfiguration `json:"encryptionConfiguration,omitempty"`
	// The format for the table.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Format *string `json:"format"`
	// The metadata for the table.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	Metadata *TableMetadata `json:"metadata,omitempty"`
	// The name for the table.
	//
	// Regex Pattern: `^[0-9a-z_]*$`
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The namespace to associated with the table.
	//
	// Regex Pattern: `^[0-9a-z_]*$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	Namespace    *string                                  `json:"namespace,omitempty"`
	NamespaceRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"namespaceRef,omitempty"`
	// The storage class configuration for the table. If not specified, the table
	// inherits the storage class configuration from its table bucket. Specify this
	// parameter to override the bucket's default storage class for this table.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	StorageClassConfiguration *StorageClassConfiguration `json:"storageClassConfiguration,omitempty"`
	// The Amazon Resource Name (ARN) of the table bucket to create the table in.
	//
	// Regex Pattern: `^(arn:aws[-a-z0-9]*:[a-z0-9]+:[-a-z0-9]*:[0-9]{12}:bucket/[a-z0-9_-]{3,63})$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	TableBucketARN *string                                  `json:"tableBucketARN,omitempty"`
	TableBucketRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"tableBucketRef,omitempty"`
	// A map of user-defined tags that you would like to apply to the table that
	// you are creating. A tag is a key-value pair that you apply to your resources.
	// Tags can help you organize, track costs for, and control access to resources.
	// For more information, see Tagging for cost allocation or attribute-based
	// access control (ABAC) (https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging.html).
	//
	// You must have the s3tables:TagResource permission in addition to s3tables:CreateTable
	// permission to create a table with tags.
	Tags map[string]*string `json:"tags,omitempty"`
}

// TableStatus defines the observed state of Table
type TableStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time the table bucket was created at.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The metadata location of the table.
	// +kubebuilder:validation:Optional
	MetadataLocation *string `json:"metadataLocation,omitempty"`
	// The date and time the table was last modified on.
	// +kubebuilder:validation:Optional
	ModifiedAt *metav1.Time `json:"modifiedAt,omitempty"`
	// The unique identifier of the namespace containing this table.
	// +kubebuilder:validation:Optional
	NamespaceID *string `json:"namespaceID,omitempty"`
	// The Amazon Resource Name (ARN) of the table.
	//
	// Regex Pattern: `^(arn:aws[-a-z0-9]*:[a-z0-9]+:[-a-z0-9]*:[0-9]{12}:bucket/[a-z0-9_-]{3,63}/table/[a-zA-Z0-9-_]{1,255})$`
	// +kubebuilder:validation:Optional
	TableARN *string `json:"tableARN,omitempty"`
	// The unique identifier of the table bucket containing this table.
	// +kubebuilder:validation:Optional
	TableBucketID *string `json:"tableBucketID,omitempty"`
	// The type of the table.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty"`
	// The version token of the table.
	// +kubebuilder:validation:Optional
	VersionToken *string `json:"versionToken,omitempty"`
	// The warehouse location of the table.
	// +kubebuilder:validation:Optional
	WarehouseLocation *string `json:"warehouseLocation,omitempty"`
}

// Table is the Schema for the Tables API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type Table struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TableSpec   `json:"spec,omitempty"`
	Status            TableStatus `json:"status,omitempty"`
}

// TableList contains a list of Table
// +kubebuilder:object:root=true
type TableList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Table `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Table{}, &TableList{})
}
