// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	"github.com/aws/aws-sdk-go/aws"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = &aws.JSONValue{}
	_ = ackv1alpha1.AWSAccountID("")
)

// Configuration specifying how data should be encrypted. This structure defines
// the encryption algorithm and optional KMS key to be used for server-side
// encryption.
type EncryptionConfiguration struct {
	KMSKeyARN *string `json:"kmsKeyARN,omitempty"`
	// Reference field for KMSKeyARN
	KMSKeyRef    *ackv1alpha1.AWSResourceReferenceWrapper `json:"kmsKeyRef,omitempty"`
	SSEAlgorithm *string                                  `json:"sseAlgorithm,omitempty"`
}

// Defines a single partition field in an Iceberg partition specification.
type IcebergPartitionField struct {
	Name      *string `json:"name,omitempty"`
	Transform *string `json:"transform,omitempty"`
}

// Defines a single sort field in an Iceberg sort order specification.
type IcebergSortField struct {
	Transform *string `json:"transform,omitempty"`
}

// Contains information about the most recent successful replication update
// to a destination.
type LastSuccessfulReplicatedUpdate struct {
	Timestamp *metav1.Time `json:"timestamp,omitempty"`
}

// Contains details about a namespace.
type NamespaceSummary struct {
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	CreatedBy      *string      `json:"createdBy,omitempty"`
	Namespace      []*string    `json:"namespace,omitempty"`
	NamespaceID    *string      `json:"namespaceID,omitempty"`
	OwnerAccountID *string      `json:"ownerAccountID,omitempty"`
	TableBucketID  *string      `json:"tableBucketID,omitempty"`
}

// Specifies a destination table bucket for replication.
type ReplicationDestination struct {
	DestinationTableBucketARN *string `json:"destinationTableBucketARN,omitempty"`
}

// Contains status information for a replication destination, including the
// current replication state, last successful update, and any error messages.
type ReplicationDestinationStatusModel struct {
	DestinationTableBucketARN *string `json:"destinationTableBucketARN,omitempty"`
	FailureMessage            *string `json:"failureMessage,omitempty"`
}

// Contains details about a schema field.
type SchemaField struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type_,omitempty"`
}

// The configuration details for the storage class of tables or table buckets.
// This allows you to optimize storage costs by selecting the appropriate storage
// class based on your access patterns and performance requirements.
type StorageClassConfiguration struct {
	StorageClass *string `json:"storageClass,omitempty"`
}

// Contains details about a table bucket.
type TableBucketSummary struct {
	ARN            *string      `json:"arn,omitempty"`
	CreatedAt      *metav1.Time `json:"createdAt,omitempty"`
	Name           *string      `json:"name,omitempty"`
	OwnerAccountID *string      `json:"ownerAccountID,omitempty"`
	TableBucketID  *string      `json:"tableBucketID,omitempty"`
	Type           *string      `json:"type_,omitempty"`
}

// Details about the status of a maintenance job.
type TableMaintenanceJobStatusValue struct {
	FailureMessage   *string      `json:"failureMessage,omitempty"`
	LastRunTimestamp *metav1.Time `json:"lastRunTimestamp,omitempty"`
}

// Contains details about a table.
type TableSummary struct {
	CreatedAt        *metav1.Time `json:"createdAt,omitempty"`
	ManagedByService *string      `json:"managedByService,omitempty"`
	ModifiedAt       *metav1.Time `json:"modifiedAt,omitempty"`
	Namespace        []*string    `json:"namespace,omitempty"`
	NamespaceID      *string      `json:"namespaceID,omitempty"`
	TableBucketID    *string      `json:"tableBucketID,omitempty"`
}
